title: XEWeb
description: XEWeb blog
url: https://www.xeweb.net
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: /blog/page/:num/
markdown: kramdown
highlighter: rouge

exclude:
  - tools
  - vendor

plugins:
  - jekyll-redirect-from